### PR TITLE
Fix the fragmentary library file.

### PR DESCRIPTION
**Pull request by flanker**
the lodash lib file was broken.

### CODE REVIEW

**Comment by flanker** [comment]
Can I also ask is there a reason why using this version? 2.4.1 looks pretty old (the latest one is v3.10.1). Cheers.

**Comment by prasunsultania** [comment]
Actually, I wrote it about a year ago and haven't updated since then. I recently made it public, I will update it soon when I get time :)

**Comment by prasunsultania** [comment]
May I know what fixes have you made? Also, I see that you have removed line if(!this.suite || !this.suite._batchYielded) , this was essential, as in scheduled script mode, when script yields it avoids the library from being reloaded into memory.

**Comment by flanker** [comment]
Hi @prasunsultania 

I didn't fix or change anything.

It is just the file in this repo (https://github.com/prasunsultania/mochafornetsuite/blob/44e1c54f77cc24beaa01ff51c18af1e44ce29fe4/suite.utils.lodash.js#L653) is trunked at line 653.

I just copied the 2.4.1 lodash lib js in. Can you make sure the lodash js file in the repo is ok

**Comment by prasunsultania** [comment]
thanks, I have merged it, it took over some of my Netsuite specific changes, but I have re-written it.

**Pull request merged**
